os:
  - linux
  - osx
language: generic
sudo: required
dist: trusty
osx_image: xcode8
script:
  - eval "$(curl -sL swift.qutheory.io/ci)"
  - eval "$(curl -sL https://raw.githubusercontent.com/vapor/swift/code-cov/codecov)"
